#!/usr/bin/env node

import { readFileSync, writeFileSync } from "node:fs";
import { basename } from "node:path";

const sqlPath = process.argv[2];
if (!sqlPath) {
  console.error(`Usage: node gen-types.mjs <schema.sql> [output.ts]`);
  process.exit(1);
}

const outPath = process.argv[3] ?? sqlPath.replace(/\.sql$/, "-types.ts");
const sql = readFileSync(sqlPath, "utf-8");

// ── PG → TS type map ──────────────────────────────────────────────────────

function pgToTs(pgType) {
  const t = pgType.trim().toLowerCase();

  if (t.endsWith("[]")) {
    const inner = pgToTs(t.slice(0, -2));
    return `${inner}[]`;
  }

  if (t === "text" || t === "uuid" || t === "bytea" || t === "date") return "string";
  if (t.startsWith("character varying")) return "string";
  if (t.startsWith("timestamp") || t.startsWith("time ")) return "string";
  if (t === "boolean") return "boolean";
  if (t === "integer" || t === "smallint" || t === "real" || t === "double precision") return "number";
  if (t.startsWith("numeric")) return "string";
  if (t === "bigint") return "string";
  if (t === "jsonb" || t === "json") return "unknown";
  if (t === "interval") return "string";

  return "unknown";
}

// ── snake_case → PascalCase ───────────────────────────────────────────────

function toPascalCase(snake) {
  return snake
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

// ── Parse CREATE TABLE blocks ─────────────────────────────────────────────

const tableRe = /CREATE TABLE public\.(\w+)\s*\(([\s\S]*?)\);/g;
const colRe = /^\s{4}(\w+)\s+([\s\S]+?)(?:\s+(?:NOT NULL|DEFAULT|PRIMARY KEY|UNIQUE|CHECK|CONSTRAINT|GENERATED|REFERENCES)|\s*$)/m;

const tables = [];
let m;

while ((m = tableRe.exec(sql)) !== null) {
  const tableName = m[1];
  const body = m[2];

  const columns = [];
  const lines = body.split("\n");

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();
    if (!line || /^\s*(CONSTRAINT|PRIMARY KEY|UNIQUE|CHECK|FOREIGN KEY)/.test(line)) continue;

    const cm = line.match(colRe);
    if (!cm) continue;

    const colName = cm[1];
    let typeStr = cm[2].trim();

    // Clean up type — remove trailing commas from the capture
    typeStr = typeStr.replace(/,\s*$/, "").trim();

    const notNull = /NOT NULL/.test(line);
    const tsType = pgToTs(typeStr);

    columns.push({ colName, tsType, notNull });
  }

  if (columns.length > 0) {
    tables.push({ tableName, columns });
  }
}

// ── Emit TypeScript ───────────────────────────────────────────────────────

const lines = [];

lines.push("// Auto-generated by gen-types.mjs — do not edit by hand.");
lines.push(`// Source: ${basename(sqlPath)} (${tables.length} tables)`);
lines.push(`// Generated: ${new Date().toISOString().slice(0, 10)}`);
lines.push("");

for (const { tableName, columns } of tables) {
  const iface = toPascalCase(tableName);
  lines.push(`export interface ${iface} {`);
  for (const { colName, tsType, notNull } of columns) {
    const q = notNull ? "" : " | null";
    lines.push(`  ${colName}: ${tsType}${q};`);
  }
  lines.push("}");
  lines.push("");
}

// Mapping type: table name → interface
lines.push("/** Map of LobeHub table names to their row types. */");
lines.push("export interface LobehubTables {");
for (const { tableName } of tables) {
  const iface = toPascalCase(tableName);
  lines.push(`  "${tableName}": ${iface};`);
}
lines.push("}");
lines.push("");

// Helper: typed select shortcut
lines.push("/**");
lines.push(" * Type-safe table reference for use with PrestClient.");
lines.push(" *");
lines.push(" *   const agents = table(\"agents\");");
lines.push(" *   await client.select<agents.row>(\"lobehub\", \"public\", agents.name, opts);");
lines.push(" */");
lines.push("export function table<K extends keyof LobehubTables>(name: K) {");
lines.push("  return { name } as { name: K; row: LobehubTables[K] };");
lines.push("}");
lines.push("");

writeFileSync(outPath, lines.join("\n"));
console.log(`Wrote ${tables.length} interfaces → ${outPath}`);
